---
title: "Notas de estudo para certificação ANCORD"
description: ""
author:
  - name: Victor Batista
    url: https://jvbatista1.github.io/
    langid: pt
date: 06/22/2025
categories: [Notas, ANCORD] # self-defined categories
citation: 
  url: https://jvbatista1.github.io/posts/20250618_apisguru/ 
image: apis_guru.svg
draft: true # setting this to `true` will prevent your post from appearing on your listing page until you're ready!

---

# Assessor de investimentos
## Atividade de AI
 - Brasil, Bolsa, Balcão
 - Intermediário
 - BTG, Banco, Corretora, XP, Santander, Bradesco, Itaú

Assessores de investimentos são contratados pelas intermediárias (preposto) para fazer o aumento da capacidade de produtos.
Instrução CVM 178/23

Assessor de Investimentos PF: Agência bancária, escritório
Assessor de Investimentos PJ: Gerentes, agente. SA ou LTDA

### Produtos distribuídos pelos AI
  - Ações
  - Derivativos
  - Fundos
  - CDB, RDB, LCi, LCA, LF, LC,
  - CRI, CRA
  - COE

### Atividade do AI
PRP: Prospectar, recepção e prestação de informações

### Constituição do AI
Mudanças recentes é regida pela CVM 178/23

Hoje: Pode ser ltda, sa, ai pode ser pf, pj

AIPJ antes tinha exclusividade, hoje não mais. 
Sociedade não precisa mais ser só AI

AIPF também não tem mais exclusividade caso ele esteja vinculado diretamente ao intermediário.

AIPF também pode estar vinculado a um escritório (AIPJ)

AIPJ é possível ter atividades complementares desde que não tenha atividades conflitantes, tais quais:

- Administração de carteira de val mob
- Consultoria de VM
- Análise de VM

### Diretor responsável
Sócio ADM do escritório que presta informações à CVM

  - presta informações
  - responde órgãos reguiladores e entidade credenciadora
  - responsável por políticas dos intermediários
  - prevenção do exercício das atividades
  - preservação de dados e infos dos clientes

## Exigências de cadastramento de AI
  - ter concluído o ensino médio
  - ter sido aprovado nos exames de qualificação técnica
  - ter aderido ao código de conduta profissional
  - não estar inabilitado ou suspenso para o exercídio de cargo em IF e demais entidades autorizadaas pelo CVM, BACEN SUSEP ou PREVIC (tomar cuidado com todo o sistema)
  - não haver sido condenado criminalmente
  - não estar impedido de administrar seus bens em razão de decisão judicial

Qualificação técnica, ética e questão de impedimentos legais

  - CNPJ (ltda, sa, ...)
  - tenha sede no país
  - tenha atividade de assessor de investimento
  - indique um diretor responsável (sócio administrador)

## Veadções AI pessoa natual (pessoa física)
  - Atuar como AIPF e como sócio, empregado ou contratado de AIPJ
  - Atuar como sócio, empregado ou contratado de mais de uma AIPJ

## Suspensão e cancelamento AI
Seção iii e iv da cvm 178/23
  - pedida pelo próprio AI mediante comprovação de que não esteja mais em atividade
  - até 36 meses. mais do que isso é cancelamento

## cancelamento (10 dias úteis para recorrer)
  - pedido pelo próprio ai
  - vícios ou falhas no processo de cancelamento
  - perda de condição necessária
  - apliccação de penalidade pela ANCORD
  - descumprimento das condições estabelecidas no PEC
  - penalidade pela CVM
  - suspensão superior a 36 meses

Não atualização dos dados multa de 100 reais diário

## Materiais de divulgação AI
O AI deve fazer referência a todos os intermediários, como contratantes, identificando o ai como contratado e apresentar dados de contato da ouvidoria dessas instituições.

Se vinculado a mais de um intermediário, abster-se de fazer referencias a produtos e infos que possam provocar dúvidas d equal intermediário se refere. O cliente não pode ficar com dúvida sobre qual intermediário se refere o produto.

AIPJ deve informar na internet a relação dos ai que sejam sócios, empregados ou contratados. Transparência.

## é vedado
adoção de logotipos desacompanhados de identificação do intermediário com no mínimo igual destaque
vale para apostilas, cursos e palestras

## Práticas vedadas AI
Receber de clientes ou em nome deles. Entregar numerário, títulos, vm ou outros ativos. REssalva para recebimento de remuneração por serviços complementares e não conflitantes.
Ser procurador ou representante de clientes para intermediários.
Contratar com clientes ou realizar, mesmo que grátis, serviços de administraçaõ de carteira, contultoria ou análise de vm
Atuar como preposto de intermediário para o qual não tenha contrato
delegar a terceiros a exec de serviços que constituam obj de contrato.
usar senhas ou assinaturas eletrônicas dos clientes para transmissão de ordens
Confeccionar extratos contendo informações sobre operações realizadas ou posições em aberto. Não pode fazer, só encaminhar.

# Lavagem de Dinheiro
Dinheiro sujo. Orígem ilícita. Dar orígem aparantemente lícita (hotel, posto)
Não confunda lavagem com sonegação.
Políticos utilizando empreiteiras:

- Doação de campanha
- Carros, imóveis
- Consultorias, palestras
- Paraísos fiscais
- Empresas de fachada

Pena: prisão de 3 a 10 anos + multa (20 milhões). Aumenta em 2/3 se fizer parte de orcim, reduz em 2/3 se tiver delação

Suspensão de 10 anos pra exercício de cargo de aipj

Etapas de LD (COI)

- Colocação
- Ocultação
- Integração

COAF é o órgão máximo de investigação

- Movimentações em espécie acima de 50 mil
- Movimentações suspeitas de qualquer valor

É necessário registrar o portador acima de 2 mil
Presidente + 11 diretores
KYC Know your costumer

## Investidor
Possível veto a determinados relacionamentos
Conhecimento da origem e do patrimônio do cliente
Compatibilidade de transações financeiras
Origem e destino dos recursos
Identificação de indícios de lavagem de dinheiro
manter por 10 anos 

Obriação de cadastro e KYC

  - Serviços de aplicação e recursos de terveitros (bancos)
  - Compra e venda de moeda estrangeira
  - Custódia e destreibuição de vm
  - Bolsa de valores
  - Seguradoras, corretoras, administradoras de cartão
  - Sociedades de arrendamento mercantil
  - Venda de imóveis e bens de luxo de alto valor
  - Venda de jóias e metais preciosos
  - Consultoria financeira

Avaliação interna de risco
Objetivo: verificar internamente se a IF está sendo usada para crime de LD
Elencar e classificar em baixo médio e alto risco

Nomear um diretor para prevenção de LD

## Pessoa politicamente exposta

  - Mandatos eletivos
  - Ministros da união, presidentes e diretores da adm pública
  -membros do stf, st e trf
  -procuradores gerais
  -membros dos tribunais de contas
  -secretários estaduais
  -presidente ou tesoureiros de partidos
    -chefes de estados
    -políticos
    -ocupantes de cargos gov
    -oficiais generais
    -executivos de escalões superiores de empresas públicas
    -dirigentes de partidos

Nos últimos 5 anos

# Economia
## Selic, DI e Copom
Compom - comitê de política monetária
Definir a taxa SELIC meta: taxa básica de juros
Divulgar o relatório de inflação a cada trimestre

Reuniões ordinárias 8 vezes por ano a cada 45 dias
Duração de dois dias

Selic over: taxa média efetiva definida pelo próprio mercado (juros compostos, 252 dias)

CDI: taxa média efetiva sem lastro em título público -- e sim em certificados

## Produto Interno Bruto
Soma de todos os bens e serviços finais produzidos em um país.

Fórmula do PIB sob ótimca do consumo: Y=C+I+G+(X-M)

## Índices de inflação
Aumento médio generalizado dos preços
Obj do bacen: asssegurar a estabilidade dos preços

IPCA
Índice de preços ao consumidor amplo
Calculado e divulgado pelo IBGE
Índice oficial de inflação no BR
Famílias com renda mensal de 1 a 40 sm

IGP-M
Índice Geral do preços ao mercado
FGV, mensal
IPA (atacado) (60%), IPC (30%), INCC (10%)

Dólar - atacado

## Taxa de câmbio
Taxa PTAX - taxa oficial de câmbio
importação prefere dolar depreciado, exportador o contrário.
BACEN faz política cambial

  - Fixa
  - Flutuante
  - Suja

## Taxa referencial
Referência para atualização monetária
Índice de correção monetária, calculado e divulgado pelo BACEN, incide sobre popança, FGTS e crédito imobiliário
$$
TR = \frac{TBF}{R}
$$
Divide a méias das LTNs (TBF) pelo redutor (R)
Mensal

## Política monetária
Expansionista (+consumo) ou contracionista (-consumo)

Depósito compulsório 70% (BACEN). O banco só vai poder emprestar 30 reais
Depósito compulsório 40% (BACEN). O banco só vai poder emprestar 60 reais

Redesconto bancário: empréstimo do BACEN

Open market: compra de títulos públicos em reserva dos bancos
compra: expansionista
venda: contracionista

## Política fiscal
Superávit primário vs défict primário
Consolidado: União, estados, municípios e empresas estatais
Expansionismo: mais consumo

## Conceitos básicos de finanças
Taxa real = taxa nominal - inflação
Fórmula de Fisher

Juros simples (taxa proporcional) vs juros compostos (taxa equivalente)

# Sistema financeiro nacional
Transferência de grana

## Conselho monetário nacional - CMN
Composto pelo Bacen e Cvm
Ministro da Fazenda, Ministro do Planejamento e Orçamento e Presidente do Bacen
100% normativo
Orientar a aplicação dos recursos das ins financeiras
Zelar pela liquidez e solvencia
Coordenar
Disciplinar
Fixar diretrizes

## Bacen
Executor. Regular a oferta de dinheiro. Assegurar a estabilidade de preços no país.
Controlar a inflação
2021 garantia de autonomia do Banco Central

Autarquia vinculada de Natureza Especial
Faz cumprir as determinações do CMN
Até nove membros na diretoria
Mandatos alternados com o presidente

Formular e executar
Emitir papel moeda
Receber compulsórios
Exercer controle de crédito
Administrar sistema de pagamentos
Fiscalizar
Executar serviços de meio circulante
Zelar, fomentar pleno emprego e estabilidade

Também é normativo

## Comissão de valores mobiliários CVM
Bacen dos valores mobilários

- Ações
- Debêntures e notas promissórias
- cotas de fundos
- derivativos

Autarquia vinculada ao MF
Zelador do mercado de capitais

Estimular a formação de poupança e aplicação em vm
Protege os investidores
Regular o mercado
Condenar efetivamente os responsáveis por infrações
Assegurar o acesso público às informações

## Conselho nacional de seguros privados -- CNSP
Igual ao CMN, mas para seguros privados
Normativo, o executor é a SUSEP

Seguro, resseguro, previdência aberta e capitalização

## Conselho Nacional de Previdência Complementar -- CNPC
Igual ao CNSP, mas para previdência fechada
Normativo, o executor é a PREVIC

## Tesouro nacional
Responsável pelos títulos públicos federais
LTN, LFT
Tirou a emissão de títulos do bacen

Gerir as contas públicas
Zelar pelo eq fiscal
Vinculado ao MF
Administra a dívida pública federal
Emissor dos títulos
Tesouro Direto

## B3
Uma bolsa de valores é um local onde se negociam títulos
Corretagem (corretora ou distribuidora); Emolumentos

Não negociam títulos públicos

Liquidação compensação de ativos de RV
Registro de operações de títulos de renda
É uma sa privada
Única bolsa de valores BR

Rebalanceamento da carteira a cada 4 meses

BSM é a CVM da B3. Autorregulação. Administra o MRP e tem orçamento próprio.

## Sistema de pagamentos brasileiro
Processamento e liquidação de opraçõe com transferendia ce dundos, ativos financeiros, modeda e valores modiliários

- Compensação de cheque
- Tranferencia de fundos
- Liquidação de ordens eletronicas
- Liquidação de bolsas e futuros

## FGC e FGCoop
Fundo garantidor de crédito. Garantir o risco. É um seguro.
O teto é 250mil por cpf e por instituição

Associação civil privada

- Depósitos
- LC
- LH
- LCI
- LCA

Debenture não tem, LF, titulos públicos não tem, cotas de fundo tbm
Na conta conjunta só tem garantia para um cpf

Limite greal de 1mm por período de 4 anos

# Insituições e intermediadores financeiros
## Bancos comerciais
Intermediário entre superavitários e deficitários
Operações passivas: depósito a vista, depósito a prazo (dívidas com o usuário)
Depósito a vista = conta corrente
deposito a prazo = certificado de depósito bancário (cbd)
Cria moeda

Deve ser SA
Expressão Banco deve estar no nome

## Banco de investimentos
Depósito a prazo
Operações ativas: empréstimo de médio e longo prazo
Deve ser SA privada
Principais operações: adm de fundos, coordenam IPO/Underwriting
Repasses de recursos oficiais de cráidto
empréstimo de capital fixo e de giro

## Bancos múltiplos
Várias carteiras (2 ou mais)
- Investimentos (obrigatória ou comercial)
- Comercial (depósito a vista) (obrigatória ou investimentos)
- Crédtio imobiliário
- Arrendamento mercantil (leasing)
- SCFI (financeiras)
- Bancos de desenvolvimento (público)

Surgiram com a intenção de racionalizar o sistema bancário
Deve ser uma sociedade anônima (ações)
Expressão banco deve estar no nome
Pode publicar um único balanço consolidando todas as carteiras

Não pode captar através de debentures

## Caixa Econômica Federal
Fomentar o mercado imobiliário
Programas sociais

- FGTS, PIS e Seguro desemprego
- Jogos lotéricos
- Programas sociais
- Empresa 100% pública
- Sede em Brasília - Vinculado ao MF

## BNDES
Financiamento de Longo prazo
Investimentos em todos os setores da economia
Tem o finame, responsável pelo financiamento de compra e venda de máquinas (crédito industrial)
Tem o BNDESPar, comprar ações de empresas

- Financiamento de Investimentos
- Subscrição de valores mobiliários
- Prestação de garantias
- Recursos para projetos sociais, culturais e tecnológicos
- Empresa pública
- Não é um banco de desenvolvimento
- Possui atuação anticíclica
- Vinculado ao MF

## Cooperativas de crédito
Muito similar a um banco comercial. Também pode captar por depósito à vista
As duas pontas precisam ser um cooperado

- Instituição financeira formdada por assossiacod
- Cooperados são conos e usuários
- participam da gestão
- não visa lucros
- lucro é repartido entre cooperados (sobras)
- supervisão do bacen
- FGCoop (250 mil)
- Constituídas com no mínimo 20 pessoas

## Crédito imobiliário
Sistema Financeiro da Habitação
- intervenção do governo federal
- limite máximo de valor de imóvel
- funding: poupança, fgts, programas do governo

Sistema financeiro imobiliário
- taxas de mercado
- recursos livres
- sem restrições de financiamento

## Financeiras
Op Passivas: Letra de câmbio (LC), RDB
Op. Passivas: CDC, crediário, capital de giro

empréstimo (sem destinação específica) vs financiamento(com destinação)

- Deve ser sa
- não pode ter cc
- deve conter a expressão "crédito, financiamento e investimento" no nome

## Corretoras e distribuidores de VM
Realizam as mesmas operações
Homebroker ou mesa de operações

- Intermediaçõa de operaço~es
- administração de clubes e fundos
- operações de compra e venda de metais preciosos, câmbio e conta margem
- distribuiçõa de titulos
- supervisão conjunta do bacen e cvm

## Corretoras de câmbio
- intermediam operçaões com moeda estrangeira
- envio e recebimento de valores do exterior (até 100 mil dólares)
- operações vinculadas de exportação e importação (até 100 mil dólares)

## Bolsas internacionais
- S&P 500 ações dos eua
  - cobre 80% do valor de mercado das ações em NY
- DJIA 
  - 30 maiores  empresas cotadas nos eua
- Nasdaq
  - nasdaq composite: todas as ações negociadas
  - nasdaq 100: 100 maiores empresas de tecnologia

# Administração de risco
## Risco de mercado, crédito e liquidez
Probabilidade de ter um resultado diferente do esperado inicialmente
Não pode ser totalmente eliminado, mas deve ser minimizado
Crédito, legal, liquidez, sobreano, operacional, mercado e cambial

Small caps (empresas com valor de mercado baixo), menor liquidez

### Risco de mercado
Oscilação preço por condições naturais de mercado

### Risco de crédito
Perigo de levar calote. Ações não tem risco de crédito.

### Risco de liquidez
Poucos compradores, preço cai.

Risco de reinvestimento: o mercado estar pior quando o fluxo entrar na conta
## Risco operacional
- Erros humanos
- Falhas de sistemas
- Fraudes

## Diversificação
Risco não sistemático vs risco sistemático

::: {.columns}
::: {.column}
Risco não sistemático
Especifico do ativo
Diversificado
::: {.column}
risco sistemático
Sistema economico
não diversificavel
:::

## VAR, Stop Loss, Back test e stress test

VAR Perda potencial máxima de um investimento para um período de tempo (ao dia)
validado pelo backtest
Stress test, casos extremos
stop loss utilizado para limitar as perdas

## Duration
Prazo de um título
Maior prazo, maior incerteza, maior risco, maior retorno

Título sem cupom, duration = 10 anos
Título com cupom, duration = menor que 10 anos

## Limite de oscilação e túneis de negociação
Evitar oscilações exageradas
Túneis são dinâmicos, e limites são fixos

## Sistemas de liquidaçõa e custódia
Mitigar o risco da liquidação
Selic liquida os títulos públics
B3 liquida os títulos privados
### Compensação
contraparte central garantidora
calculo de posições compradas e vendidas
controle de risco do mercado
### Liquidação
Controla e processa a troca de dinheiro por títulos
### Central depoistária
Pagamento de proventos e bonificações
Contabilização e guarda dos ativos

# Mercado de capitais
## Mercado primário e secundário
Dívida vs capital próprio
Debêntures e notas promissórias vs ações

### operação de underwriting
Oferta pública, intermediário entre emissores e compradores
Underwriters: financeiras, missões de títulos e vm
- Garantia firme
- Melhores esforços
- Residual (stand by)

Mercado primário: dinheiro vai para a empresa. Captação para a empresa.
Mercado secundário: dinheiro vai para o sócio. Liquidez para os investidores.

## Tipos de ações e riscos
Ações ordinárias (ON)
- Direito a voto
- Controle da CIA

Preferenciais (PN)
- Sem diretiro a voto
- Preferência para dividendos
- 3 ex sem dividendos ganha diretio a votos

Riscos: mercado, liquidez e crédito

## Ganhos com ações
Ganho de capital: compra por 10 e vende por 15
Distribuição de lucro: dividendos (isento) ou juros por capital próprio (IR de 15%)
É obrigado a dividir 25% do lucro em divididos
O que for retido fica com juros por capital próprio

Bonificação (grátis) e subscrição (direito de compra)

## Governança corporativa
Conjunto de processos, costumes, políticas e regulamentos que ditam a direção da empresa
Visa atrair mis investidores, garantir tranparencia e proteger acionistas
Complementar a legislação

### Segmentos de listagem
free float: livres no mercado

## ADR e BDR
Não são ações. São recibos de depósito lastreados por ações
A de América
B de Brasil

Empresa não americana emitie ações
Leva para um banco custodiante
Investidores americanos compram ADR em dólar

## ADR e BDR patrocinados e não patrocinaos e GDR
Patrocinado:
- Envolvimento direto da empresa emissora
- De acordo com regras brasileiras

Não patrocinado:
- Sem envolvimento
- De acordo com país de origem

### Níveis ADR
Nível 1: mercado de balcão
Nível 2: listado em bolsa
Nível 3: Listado em bolsa, oferta pública e captação de recurso
144a: mercado de balcão, captação de recurso

### GDR
Negociado ao redor do mundo
Negociado na moeda local

## Debêntures
S.A não financeira
Título de díveida de médio/longo prazo
Debentures simples, conversíveis ou permutáveis
Não tem FGC
- Simples: 100k + juros
- Conversível: 100k + juros ou converto em ações
- Permutável: 100 k + juros ou converte em ações de outra empresa do grupo
Pode ou não ter garantia real
Tem imposto de renda (progressivo)

## Notas promissórias - commercial paper
np até 360 dias, debeture mais de 360 dias

título de dívida de curto prazo
Tablea regressiva de ir
não há garantia real
não há gratana pelo fgc
juros pré pós ou híbridos

## Tributação em ações
Day trade: 1% na fonte, 19% dafne
Swing trade: 0,005% na fonte, 14,995% dafne

Retido na fonte: responsabilidade da corretora

Isenção: pessoa física, não day trade
Isenção: valor bruto de vendas menor que 20mil (títulos não entram)

## Banco de títulos BTC
Aluguel de ações
Operação short
direito a voto será do tomador do aluguel, ao contrário dos proventos

## Regulamento operacional do segmento bovespa
Mercaado a vista 10h 16h55
Aftermarket não negocia derivativos

- Ordem a mercado: especifica somente quantidade e ativo, execução no momento
- Ordem limitada: executada somente a preço igual ou melhor do que o esepecificado
- Ordem administrada: especifica somente quantidade e ativo, execução pela corretora
- Ordem discricionária: realizada por um admiinstrador de carteiras
- Ordem de financiamento: compra ou venda junto com outra compra ou venda de um derivativo
- Ordem stop: especifica o preço do ativo a partir do qual a ordem deve ser executada
- Ordem casada: vinculada à execução de outra ordem

- Apregoação direta: comprar e vender um mesmo ativo para diversos clientes
- Apregoação por Leilão: destaque das demais ativo lote e preço
- Apregoação por Leilão comum: permitida a interferência do vendedor e comprador a melhor preço
- Apregoação por Leilão especial: destaque das demais, somente permitida interferência pra compra
- Apregoação por oferta: demostraçaõ de interesse em comprar/vender ativos inserindo a oferta no sistema

# Outros fundos de investimento
## Fundo de índice
ETF: Fundos negociados na B3
Segue um índice e.g. IBOVESPA
- Cotas negociadas em bolsa
- Objetvio de refletir
- -Mínimo 95% do PL alocado em ativos do indice
- Lote padrão 1 cota

## FII
Fundos imobiliários que adquirem ativos do setor imobiliário

- Fundo fechado
- Dividendos isentos de IR
- Cotas negociadas em bolsa ou balcão
- Mínimo 100 cotistas
- Cotista com no máximo 10% das cotas
- Ganho de capital = IR 20%
- Distribuição de 95% de seu lucro
- Acessibilidade, gestão profissional, fácil negociação

## FIEE
Empresa emergente
- Fundo fechado
- Deve participar do processo decisório
- devem manter 90% do patrimonio

## FIP
Ativos: cias abertas, cias fechadas, sociedades ltda
Compra ativos para participar do processo decisório
- Fundo fechado
- 90% em ações D simples e títulos conversíveis em ações ordinárias

## FIDC
Direito creditório
Cheques, duplicatas, cc, outros

- Mínimo 50% em DC
- Não tem valor mínimo de aplicação inicial
- Cota: senior ou subordinada
- fundo aberto ou fechado

- Fomento mercantil
- Financeiro
- Agro industria comercio
- Outros

# Securitização de recebíveis
## Conceito
Direito de crédito
Vender os direitos de crédito para uma companhia securitização (SPE)

## CRI e CRA
Igual a um FIDC, mas ao invés de um fundo, é um ativo próprio
Certificado de recebíveis de imóveis ou do agro

# Clubes de investimentos em ações
Mínimo de 67% de ações
Limite mínimo de 3 e máximo de 50 pessoas
Máximo de 40% para cada cotista

Gestão: próprios cotistas ou gestão profisional

# Matemática financeira
## Taxa equivalente: programação na HP
## Cálculos básicos
## Análise de investimentos
- CF0 = investimento inicial
- CFj = fluxo de caixa periódico
- Nj = repetir valor
- NPV = Valor presente líquido
- IRR = taxa interna de retorno

## Cálculos com títulos de renda fixa

# Derivativos
## Introdução
Contratos que se referem a um ativo principal
1. Mercado a termo
2. SWAP
3. Opções
4. Mercado a futuro

Hedger - Especulador - Arbitrador

## Mercado a termo
Vai pagar só no futuro por um preço pré-definido
Cheque pre-datado
- Compra ou venda de algo em data futura com preço previamente definido
- 16 a 999 dias corridos
- Sem padrão e sem prêmio
- Sem ajuste diário
- Apenas compradores precisam dar margem de garantia

## Swap
Taxa pré-fixada (e.g. câmbio)
- Sem padrão
- Renda fixa (tabela regressiva ir)
- Mais comuns: índices, taxas de juros, e moedas
- ferramenta de troca

## Mercado de opções
Tem prêmio
Comprar Call: direito de comprar
Comprar Put: direito de vender

### Call
Opção de compra. 
Titular (aposta na alta) e lançador: Pode ou não exercer

### Put
Opção de venda.
Titular (aposta na queda) e lançador: Pode ou não exercer também

Opções européias: somente na data do vencimento. Opções americanas: a qualquer momento até a data do exercício

## Estratégias com opções
Gráficos

## Mercado futuro
Comprado: aposta na alta
Vendido:aposta na baixa
Ajuste diário em d+1
Não tem risco de crédito

Hedge:opera vendido
Padronizados

Preços futuros podem inclusive ser inferiores aos preços a vista
Garantias devem ser depositadas antes do início das operações no mercado futuro