---
title: "Notas de estudo para certificação ANCORD"
description: ""
author:
  - name: Victor Batista
    url: https://jvbatista1.github.io/
    langid: pt
date: 06/22/2025
categories: [Notas, ANCORD] # self-defined categories
citation: 
  url: https://jvbatista1.github.io/posts/20250618_apisguru/ 
image: apis_guru.svg
draft: true # setting this to `true` will prevent your post from appearing on your listing page until you're ready!

---

# Assessor de investimentos
## Atividade de AI
 - Brasil, Bolsa, Balcão
 - Intermediário
 - BTG, Banco, Corretora, XP, Santander, Bradesco, Itaú

Assessores de investimentos são contratados pelas intermediárias (preposto) para fazer o aumento da capacidade de produtos.
Instrução CVM 178/23

Assessor de Investimentos PF: Agência bancária, escritório
Assessor de Investimentos PJ: Gerentes, agente. SA ou LTDA

### Produtos distribuídos pelos AI
  - Ações
  - Derivativos
  - Fundos
  - CDB, RDB, LCi, LCA, LF, LC,
  - CRI, CRA
  - COE

### Atividade do AI
PRP: Prospectar, recepção e prestação de informações

### Constituição do AI
Mudanças recentes é regida pela CVM 178/23

Hoje: Pode ser ltda, sa, ai pode ser pf, pj

AIPJ antes tinha exclusividade, hoje não mais. 
Sociedade não precisa mais ser só AI

AIPF também não tem mais exclusividade caso ele esteja vinculado diretamente ao intermediário.

AIPF também pode estar vinculado a um escritório (AIPJ)

AIPJ é possível ter atividades complementares desde que não tenha atividades conflitantes, tais quais:
  - Administração de carteira de val mob
  - Consultoria de VM
  - Análise de VM

### Diretor responsável
Sócio ADM do escritório que presta informações à CVM
  - presta informações
  - responde órgãos reguiladores e entidade credenciadora
  - responsável por políticas dos intermediários
  - prevenção do exercício das atividades
  - preservação de dados e infos dos clientes

# Exigências de cadastramento de AI
  - ter concluído o ensino médio
  - ter sido aprovado nos exames de qualificação técnica
  - ter aderido ao código de conduta profissional
  - não estar inabilitado ou suspenso para o exercídio de cargo em IF e demais entidades autorizadaas pelo CVM, BACEN SUSEP ou PREVIC (tomar cuidado com todo o sistema)
  - não haver sido condenado criminalmente
  - não estar impedido de administrar seus bens em razão de decisão judicial

Qualificação técnica, ética e questão de impedimentos legais

  - CNPJ (ltda, sa, ...)
  - tenha sede no país
  - tenha atividade de assessor de investimento
  - indique um diretor responsável (sócio administrador)

## Veadções AI pessoa natual (pessoa física)
  - Atuar como AIPF e como sócio, empregado ou contratado de AIPJ
  - Atuar como sócio, empregado ou contratado de mais de uma AIPJ

# Suspensão e cancelamento AI
Seção iii e iv da cvm 178/23
  - pedida pelo próprio AI mediante comprovação de que não esteja mais em atividade
  - até 36 meses. mais do que isso é cancelamento

## cancelamento (10 dias úteis para recorrer)
  - pedido pelo próprio ai
  - vícios ou falhas no processo de cancelamento
  - perda de condição necessária
  - apliccação de penalidade pela ANCORD
  - descumprimento das condições estabelecidas no PEC
  - penalidade pela CVM
  - suspensão superior a 36 meses


# Materiais de divulgação AI
O AI deve fazer referência a todos os intermediários, como contratantes, identificando o ai como contratado e apresentar dados de contato da ouvidoria dessas instituições.

Se vinculado a mais de um intermediário, abster-se de fazer referencias a produtos e infos que possam provocar dúvidas d equal intermediário se refere. O cliente não pode ficar com dúvida sobre qual intermediário se refere o produto.

AIPJ deve informar na internet a relação dos ai que sejam sócios, empregados ou contratados. Transparência.

## é vedado
adoção de logotipos desacompanhados de identificação do intermediário com no mínimo igual destaque
vale para apostilas, cursos e palestras

# Práticas vedadas AI
Receber de clientes ou em nome deles. Entregar numerário, títulos, vm ou outros ativos. REssalva para recebimento de remuneração por serviços complementares e não conflitantes.
Ser procurador ou representante de clientes para intermediários.
Contratar com clientes ou realizar, mesmo que grátis, serviços de administraçaõ de carteira, contultoria ou análise de vm
Atuar como preposto de intermediário para o qual não tenha contrato
delegar a terceiros a exec de serviços que constituam obj de contrato.
usar senhas ou assinaturas eletrônicas dos clientes para transmissão de ordens
Confeccionar extratos contendo informações sobre operações realizadas ou posições em aberto. Não pode fazer, só encaminhar.
